---
version: '3.6'
volumes:
  cockroachdb:

services:
  cockroachdb:
    container_name: ${DOCKER_NAME}-example-cockroachdb
    image: cockroachdb/cockroach:v22.1.9
    volumes:
      - type: bind
        source: certs
        target: /cockroach/certs
      - type: volume
        source: cockroachdb
        target: /cockroach/cockroach-data
    ports:
      - 26257:26257
      - 8080:8080
    command: start-single-node --certs-dir=/cockroach/certs

  web-server:
    container_name: ${DOCKER_NAME}-example-server
    image: ${PACKAGE_NAME}:latest
    ports:
      - ${HOST_PORT_REST}:${DOCKER_PORT_REST}
      - ${HOST_PORT_GRPC}:${DOCKER_PORT_GRPC}
    volumes:
      - type: bind
        source: "${SOURCE_PATH}/certs/ca.crt"
        target: "/etc/ca-certificates/cockroachdb-ca.crt"
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr", "localhost:${DOCKER_PORT_GRPC}"]
      interval: 2s
      timeout: 1s
      retries: 3
    env_file:
      - .env
    environment:
      - PG__USER
      - PG__DBNAME
      - PG__PASSWORD
      - PG__HOST
      - PG__PORT
      - PG__SSLMODE
      - DB_CA_CERT

  example:
    links:
      - cockroachdb
      - web-server
    depends_on:
      web-server:
        condition: service_healthy
    container_name: ${DOCKER_NAME}-example
    image: ${RUST_IMAGE_NAME}:${RUST_IMAGE_TAG}
    volumes:
      - type: bind
        source: "${SOURCE_PATH}/"
        target: "/usr/src/app"
      - type: bind
        source: "${SOURCE_PATH}/.cargo/registry"
        target: "/usr/local/cargo/registry"
    environment:
      - SERVER_HOSTNAME
      - SERVER_PORT_GRPC
      - SERVER_PORT_REST
      - EXAMPLE_TARGET
    command: cargo run --manifest-path "${CARGO_MANIFEST_PATH}" --example "${EXAMPLE_TARGET}"
