[package]
description = "Arrow storage service GRPC server"
edition     = "2021"                                                       # Allowed values are 2015, 2018, 2021
homepage    = "https://www.arrowair.com/docs/documentation/services/intro"
keywords    = ["vtol", "server", "storage"]                                # max 5
license     = "BUSL-1.1"
name        = "svc-storage"
repository  = "https://github.com/Arrow-air/svc-storage"
version     = "0.9.0-develop.1"

categories = [
  "aerospace::drones",
  "aerospace::protocols",
] # max 5 -- https://crates.io/category_slugs

[features]
vendored-openssl = ['openssl/vendored']

[dependencies]
anyhow              = "1.0"
cargo-husky         = "1"
chrono              = "0.4"
config              = "0.13"
deadpool            = "0.9"
deadpool-postgres   = { version = "0.10", features = ["serde", "rt_tokio_1"] }
dotenv              = "0.15"
futures             = "0.3"
geo-types           = "0.7"
lazy_static         = "1.4"
log                 = "0.4"
native-tls          = "0.2"
num-derive          = "0.3"
num-traits          = "0.2"
once_cell           = "1.16"
openssl             = "0.10"
ordered-float       = "3.3.0"
postgres-native-tls = "0.5"
prost               = "0.11"
prost-types         = "0.11"
router              = { git = "https://github.com/Arrow-air/lib-router.git", branch = "main" }
serde               = "1.0"
serde_json          = "1.0"
serde_yaml          = "0.9"
thiserror           = "1.0"
tokio               = { version = "1.20", features = ["full"] }
tokio-postgres      = { version = "0.7", features = ["with-uuid-1"] }
tonic               = "0.8"
tonic-health        = "0.7"
uuid                = { version = "1.2", features = ["v4"] }

[dependencies.log4rs]
features = [
  "background_rotation",
  "rolling_file_appender",
  "json_format",
  "gzip",
]
version = "1.2"

[dependencies.postgres-types]
features = [
  "with-chrono-0_4",
  "with-uuid-1",
  "with-serde_json-1",
  "with-geo-types-0_7",
]
version = "0.2"

[build-dependencies]
tonic-build = "0.8"

[dev-dependencies.cargo-husky]
default-features = false          # Disable features which are enabled by default
features         = ["user-hooks"]
version          = "1"
