[package]
edition = "2021"        # Allowed values are 2015, 2018, 2021
name    = "svc-storage"
version = "0.1.0"
# Rust Editions: https://doc.rust-lang.org/edition-guide/index.html

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-husky = "1"
chrono      = "0.4.19"
dotenv      = "0.15.0"
lazy_static = "1.4.0"
prost       = "0.11"
prost-types = "0.11.1"
tokio       = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic       = "0.8.1"

[build-dependencies]
tonic-build = "0.8"

[dev-dependencies.cargo-husky]
default-features = false          # Disable features which are enabled by default
features         = ["user-hooks"]
version          = "1"

[[bin]]
name = "svc-storage"
src  = "src/main.rs"
