[package]
description = "Arrow storage service GRPC server"
keywords    = ["vtol", "server", "storage"]       # max 5
name        = "svc-storage"
version     = "0.10.1-develop.1"

categories.workspace   = true
edition.workspace      = true
homepage.workspace     = true
license-file.workspace = true
repository.workspace   = true

[features]
mock             = ["rand"]
vendored-openssl = ['openssl/vendored']

[dependencies]
anyhow              = "1.0"
cargo-husky         = "1"
chrono              = "0.4"
config              = "0.13"
deadpool            = "0.9"
deadpool-postgres   = { version = "0.10", features = ["serde", "rt_tokio_1"] }
dotenv              = "0.15"
futures             = "0.3"
geo-types           = "0.7"
lazy_static         = "1.4"
lib-common          = { git = "https://github.com/Arrow-air/lib-common.git", tag = "v0.1.0" }
log                 = "0.4"
native-tls          = "0.2"
num-derive          = "0.3"
num-traits          = "0.2"
once_cell           = "1.16"
openssl             = "0.10"
ordered-float       = "3.3.0"
paste               = "1.0"
postgres-native-tls = "0.5"
prost               = "0.11"
prost-types         = "0.11"
rand                = { version = "0.8", optional = true }
serde               = "1.0"
serde_json          = "1.0"
serde_yaml          = "0.9"
thiserror           = "1.0"
tokio               = { version = "1.20", features = ["full"] }
tokio-postgres      = { version = "0.7", features = ["with-uuid-1"] }
tonic               = "0.8"
tonic-health        = "0.7"
uuid                = { version = "1.2", features = ["v4"] }

[dependencies.log4rs]
features = [
  "background_rotation",
  "rolling_file_appender",
  "json_format",
  "gzip",
]
version = "1.2"

[dependencies.postgres-types]
features = [
  "with-chrono-0_4",
  "with-uuid-1",
  "with-serde_json-1",
  "with-geo-types-0_7",
]
version = "0.2"

[build-dependencies]
tonic-build = "0.8"

[build-dependencies.svc-storage-client-grpc]
features = ["all-resources"]
git      = "https://github.com/Arrow-air/svc-storage.git"
tag      = "v0.10.1-develop.1"

[dev-dependencies]
svc-storage = { path = ".", features = ["mock"] }

[dev-dependencies.cargo-husky]
default-features = false          # Disable features which are enabled by default
features         = ["user-hooks"]
version          = "1"

[dev-dependencies.svc-storage-client-grpc]
features = ["all-resources"]
git      = "https://github.com/Arrow-air/svc-storage.git"
tag      = "v0.10.1-develop.1"
