[package]
description = "Arrow Storage service GRPC client"
keywords    = ["vtol", "client", "storage"]       # max 5
name        = "svc-storage-client-grpc"
version     = "0.9.0-develop.9"

categories.workspace = true
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
repository.workspace = true

[dependencies]
geo-types     = "0.7"
num-derive    = "0.3"
num-traits    = "0.2"
ordered-float = "3.3"
prost         = "0.11"
prost-types   = "0.11"
tonic         = "0.8"
uuid          = { version = "1.2", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[[example]]
name = "grpc"
