[package]
description = "Arrow Storage service GRPC client"
keywords    = ["vtol", "client", "storage"]       # max 5
name        = "svc-storage-client-grpc"
version     = "0.9.0-develop.12"

categories.workspace = true
edition.workspace    = true
homepage.workspace   = true
license.workspace    = true
repository.workspace = true

include = [
  "out/grpc/*.rs",
  "out/grpc/client/*.rs",
  "examples/**",
  "includes/**",
  "src/**",
  "tests/**",
]

[dependencies]
chrono        = { version = "0.4", optional = true }
geo-types     = "0.7"
num-derive    = "0.3"
num-traits    = "0.2"
ordered-float = "3.3"
prost         = "0.11"
prost-types   = "0.11"
rand          = { version = "0.8", optional = true }
tonic         = "0.8"
uuid          = { version = "1.2", features = ["v4"] }

[dev-dependencies]
chrono = "0.4"
rand   = "0.8"
tokio  = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build = "0.8"

[[example]]
name = "grpc"

[features]
mock = ["chrono", "rand"]
