[package]
description = "Arrow Storage service GRPC client"
keywords    = ["vtol", "client", "storage"]       # max 5
name        = "svc-storage-client-grpc"
version     = "0.10.0"

categories.workspace   = true
edition.workspace      = true
homepage.workspace     = true
license-file.workspace = true
repository.workspace   = true

include = [
  "out/grpc/*.rs",
  "out/grpc/client/*.rs",
  "examples/**",
  "includes/**",
  "src/**",
  "tests/**",
]

[dependencies]
anyhow        = "1.0"
chrono        = { version = "0.4", optional = true }
futures       = "0.3"
geo-types     = "0.7"
lib-common    = { git = "https://github.com/Arrow-air/lib-common.git", tag = "v0.1.0", optional = true }
num-derive    = "0.3"
num-traits    = "0.2"
ordered-float = "3.3"
prost         = "0.11"
prost-types   = "0.11"
rand          = { version = "0.8", optional = true }
tokio         = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic         = "0.8"
uuid          = { version = "1.2", features = ["v4"] }

[dev-dependencies]
chrono                  = "0.4"
lib-common              = { git = "https://github.com/Arrow-air/lib-common.git", tag = "v0.1.0" }
rand                    = "0.8"
svc-storage-client-grpc = { path = ".", features = ["mock", "all-resources"] }

[build-dependencies]
tonic-build = "0.8"

[[example]]
name = "grpc"

[features]
adsb = []
all-resources = [
  "adsb",
  "flight_plan",
  "itinerary",
  "pilot",
  "vehicle",
  "vertipad",
  "vertiport",
]
flight_plan = []
itinerary = []
mock = ["chrono", "rand", "lib-common"]
pilot = []
vehicle = []
vertipad = []
vertiport = []
