[package]
description = "Arrow Storage service GRPC client"
edition     = "2021"                                                       # Allowed values are 2015, 2018, 2021
homepage    = "https://www.arrowair.com/docs/documentation/services/intro"
keywords    = ["vtol", "client", "storage"]                                # max 5
license     = "BUSL-1.1"
name        = "svc-storage-client-grpc"
repository  = "https://github.com/Arrow-air/svc-storage"
version     = "0.9.0-develop.1"

categories = [
  "aerospace::drones",
  "aerospace::protocols",
] # max 5 -- https://crates.io/category_slugs

[dependencies]
geo-types     = "0.7"
num-derive    = "0.3"
num-traits    = "0.2"
ordered-float = "3.3"
prost         = "0.11"
prost-types   = "0.11"
router        = { git = "https://github.com/Arrow-air/lib-router.git", branch = "main" }
tonic         = "0.8"
uuid          = { version = "1.2", features = ["v4"] }

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[[example]]
name = "grpc"
